### PR TITLE
Fix type for "last_clean_t" (number)

### PR DESCRIPTION
**Pull request by trollvottel**
grafik

### CODE REVIEW

**Comment by copystring** [comment]
Roborock Q Revo? This needs to be fixed in the Q Revo definitions. A date cannot be a number. Needs to be a string instead.
If you want to correct your PR you'd need to fix this here: https://github.com/copystring/ioBroker.roborock/blob/dev/lib/genSpecs/gen8/q_revo/robot.js#L472

**Comment by copystring** [comment]
Indeed. The copy & paste made it the same for all robots which support last_clean_t resulting in the same warning for all of them.

**Comment by trollvottel** [comment]
Ok, I guess it's better then you fix that instead of me, I'm still lost in this project but looking around :)

**Comment by copystring** [comment]
Sure. There you go. https://github.com/copystring/ioBroker.roborock/commit/266bc8392a3ba15526e9efcfe07e4cab96322537
Thanks for bringing the issue up. I could never test this. I don't have a gen8 robot.

**Comment by trollvottel** [comment]
Closed in favor of #266bc83

**Comment by copystring** [comment]
Please test this in your setup. Does it work out for you? Does it show the correct date?

**Comment by trollvottel** [comment]
This is my first dev adapter. Do I need to reinstall or how to update?

**Comment by copystring** [comment]
You can update the same way you installed the dev version.

**Comment by trollvottel** [comment]
Should it fix the already existing object?

**Comment by copystring** [comment]
Yes, it would update the existing objects from number to string matching the returned data.

**Comment by trollvottel** [comment]
Yes it did and the message is gone. But no "type 34" messages anymore?

**Comment by copystring** [comment]
Did you delete and reinstall? Type 34 or similar messages appear only when map creation is enabled and a new map is requested.

**Comment by trollvottel** [comment]
Ah, ic, the feature was disabled. Will check now, I've added some rooms from cellar.

**Comment by copystring** [comment]
Ok. For block type 34, please continue in the Q Revo issue. Thanks!

**Pull request closed without merging**
